export const ONTARIO_BOARDS = [
  { id: 'algoma-dsb', name: 'Algoma DSB' },
  { id: 'algonquin-lakeshore', name: 'Algonquin & Lakeshore' },
  { id: 'bluewater', name: 'Bluewater' },
  { id: 'bruce-grey-catholic', name: 'Bruce-Grey Catholic' },
  { id: 'cdsb-eastern-ontario', name: 'CDSB Eastern Ontario' },
  { id: 'dsbone', name: 'DSBONE' },
  { id: 'dufferin-peel', name: 'Dufferin-Peel' },
  { id: 'durham-dsb', name: 'Durham DSB' },
  { id: 'grand-erie', name: 'Grand Erie' },
  { id: 'greater-essex-country', name: 'Greater Essex Country' },
  { id: 'hamilton-wentworth', name: 'Hamilton-Wentworth' },
  { id: 'keewatin-patricia', name: 'Keewatin-Patricia' },
  { id: 'lambton-kent', name: 'Lambton Kent' },
  { id: 'northeastern-cdsb', name: 'Northeastern CDSB' },
  { id: 'northwest-cdsb', name: 'Northwest CDSB' },
  { id: 'ottawa-catholic', name: 'Ottawa Catholic' },
  { id: 'peel-dsb', name: 'Peel DSB' },
  { id: 'pvnc-dsb', name: 'PVNC DSB' },
  { id: 'renfrew-county', name: 'Renfrew County' },
  { id: 'simcoe-county', name: 'Simcoe County' },
  { id: 'smithville-christian', name: 'Smithville Christian' },
  { id: 'thames-valley', name: 'Thames Valley' },
  { id: 'toronto-catholic', name: 'Toronto Catholic' },
  { id: 'trinity-college-school', name: 'Trinity College School' },
  { id: 'upper-canada', name: 'Upper Canada' },
  { id: 'upper-grand', name: 'Upper Grand' },
  { id: 'waterloo-region', name: 'Waterloo Region' },
  { id: 'york-catholic', name: 'York Catholic' },
];

export const SCHOOLS_BY_BOARD: Record<string, Array<{ id: string; name: string }>> = {
  'bluewater': [
    { id: 'bluewater-7s-and-8s', name: 'Bluewater 7s and 8s' },
    { id: 'bluewater-alternative-education-school', name: 'Bluewater Alternative Education School' },
    { id: 'bluewater-continuing-education-day-school', name: 'Bluewater Continuing Education Day School' },
    { id: 'bluewater-continuing-education-night-school', name: 'Bluewater Continuing Education Night School' },
    { id: 'bruce-peninsula-district-school', name: 'Bruce Peninsula District School' },
    { id: 'ecole-john-diefenbaker-senior-school', name: 'École John Diefenbaker Senior School' },
    { id: 'georgian-bay-secondary-school', name: 'Georgian Bay Secondary School' },
    { id: 'grey-highlands-secondary-school', name: 'Grey Highlands Secondary School' },
    { id: 'kincardine-district-secondary-school', name: 'Kincardine District Secondary School' },
    { id: 'owen-sound-district-secondary-school', name: 'Owen Sound District Secondary School' },
    { id: 'peninsula-shores-district-school', name: 'Peninsula Shores District School' },
    { id: 'saugeen-district-secondary-school', name: 'Saugeen District Secondary School' },
    { id: 'secondary-remote-school', name: 'Secondary Remote School' },
    { id: 'walkerton-district-community-school', name: 'Walkerton District Community School' },
  ],
  'grand-erie': [
    { id: 'grand-erie-7s-and-8s', name: 'Grand Erie 7s and 8s' },
    { id: 'brantford-collegiate-institute-and-vs', name: 'Brantford Collegiate Institute and V.S.' },
    { id: 'cayuga-secondary-school', name: 'Cayuga Secondary School' },
    { id: 'delhi-district-secondary-school', name: 'Delhi District Secondary School' },
    { id: 'dunnville-secondary-school', name: 'Dunnville Secondary School' },
    { id: 'gela-summer-school', name: 'GELA Summer School' },
    { id: 'gela-virtual-school', name: 'GELA Virtual School' },
    { id: 'grand-erie-learning-alternatives', name: 'Grand Erie Learning Alternatives' },
    { id: 'hagersville-secondary-school', name: 'Hagersville Secondary School' },
    { id: 'mckinnon-park-secondary-school', name: 'McKinnon Park Secondary School' },
    { id: 'north-park-collegiate-and-vs', name: 'North Park Collegiate and V.S.' },
    { id: 'paris-district-high-school', name: 'Paris District High School' },
    { id: 'pauline-johnson-collegiate-and-vocational-school', name: 'Pauline Johnson Collegiate and Vocational School' },
    { id: 'simcoe-composite-school', name: 'Simcoe Composite School' },
    { id: 'tollgate-technological-skills-centre', name: 'Tollgate Technological Skills Centre' },
    { id: 'valley-heights-secondary-school', name: 'Valley Heights Secondary School' },
    { id: 'waterford-district-high-school', name: 'Waterford District High School' },
  ],
  'upper-canada': [
    { id: 'ucdsb-7s-and-8s', name: 'UCDSB 7s and 8s' },
    { id: 'almonte-district-hs', name: 'Almonte & District HS' },
    { id: 'athens-district-hs', name: 'Athens District HS' },
    { id: 'brockville-collegiate', name: 'Brockville Collegiate' },
    { id: 'carleton-place-hs', name: 'Carleton Place HS' },
    { id: 'char-lan-district-hs', name: 'Char-Lan District HS' },
    { id: 'cornwall-collegiate-vs', name: 'Cornwall Collegiate VS' },
    { id: 'gananoque-ss', name: 'Gananoque SS' },
    { id: 'glengarry-district-hs', name: 'Glengarry District HS' },
    { id: 'north-dundas-dhs', name: 'North Dundas D.H.S.' },
    { id: 'north-grenville-dhs', name: 'North Grenville D.H.S.' },
    { id: 'perth-district-ci', name: 'Perth & District CI' },
    { id: 'rideau-district-hs', name: 'Rideau District HS' },
    { id: 'rockland-district-hs', name: 'Rockland District HS' },
    { id: 'russell-hs', name: 'Russell HS' },
    { id: 'seaway-district-hs', name: 'Seaway District HS' },
    { id: 'smiths-falls-dci', name: 'Smiths Falls D.C.I.' },
    { id: 'south-grenville-dhs', name: 'South Grenville DHS' },
    { id: 'st-lawrence-secondary-school', name: 'St. Lawrence Secondary School' },
    { id: 'tagwi-ss', name: 'Tagwi SS' },
    { id: 'thousand-islands-secondary', name: 'Thousand Islands Secondary' },
    { id: 'tr-leger', name: 'TR Leger' },
    { id: 'vankleek-hill-ci', name: 'Vankleek Hill CI' },
  ],
  'northwest-cdsb': [
    { id: 'northwest-7s-and-8s', name: 'Northwest 7s and 8s' },
    { id: 'dryden-high-school', name: 'Dryden High School' },
    { id: 'sioux-north-high-school', name: 'Sioux North High School' },
  ],
  'dufferin-peel': [
    { id: 'dufferin-peel-7s-and-8s', name: 'Dufferin-Peel 7s and 8s' },
    { id: 'ascension-of-our-lord-ss', name: 'Ascension of Our Lord SS' },
    { id: 'bj-fleming-adult-learning-center', name: 'BJ Fleming Adult Learning Center' },
    { id: 'cardinal-ambrozic', name: 'Cardinal Ambrozic' },
    { id: 'cardinal-leger', name: 'Cardinal Leger' },
    { id: 'cec-education-forward-school', name: 'CEC Education Forward School' },
    { id: 'countryside-secondary', name: 'Countryside Secondary' },
    { id: 'father-michael-goetz-ss', name: 'Father Michael Goetz SS' },
    { id: 'holy-name-of-mary', name: 'Holy Name of Mary' },
    { id: 'iona-catholic-ss', name: 'Iona Catholic SS' },
    { id: 'john-cabot', name: 'John Cabot' },
    { id: 'loyola-catholic-ss', name: 'Loyola Catholic SS' },
    { id: 'notre-dame-catholic-ss', name: 'Notre Dame Catholic SS' },
    { id: 'our-lady-of-mount-carmel-ss', name: 'Our Lady of Mount Carmel SS' },
    { id: 'philip-pocock', name: 'Philip Pocock' },
    { id: 'robert-f-hall-catholic-ss', name: 'Robert F. Hall Catholic SS' },
    { id: 'st-aloysius-gonzaga-ss', name: 'St. Aloysius Gonzaga SS' },
    { id: 'st-augustine-ss', name: 'St. Augustine SS' },
    { id: 'st-edmund-campion', name: 'St. Edmund Campion' },
    { id: 'st-francis-xavier-ss', name: 'St. Francis Xavier SS' },
    { id: 'st-gabriel-adult-learning-centre', name: 'St. Gabriel Adult Learning Centre' },
    { id: 'st-joan-of-arc', name: 'St. Joan of Arc' },
    { id: 'st-joseph-ss', name: 'St. Joseph SS' },
    { id: 'st-marcellinus', name: 'St. Marcellinus' },
    { id: 'st-marguerite-dyouville', name: "St. Marguerite d'Youville" },
    { id: 'st-martin-ss', name: 'St. Martin SS' },
    { id: 'st-michael-catholic-secondary-school', name: 'St. Michael Catholic Secondary School' },
    { id: 'st-oscar-romero-catholic-ss', name: 'St. Oscar Romero Catholic SS' },
    { id: 'st-paul-ss', name: 'St. Paul SS' },
    { id: 'st-roch-catholic', name: 'St. Roch Catholic' },
    { id: 'st-thomas-aquinas-ss', name: 'St. Thomas Aquinas SS' },
  ],
  'toronto-catholic': [
    { id: 'tcdsb-7s-and-8s', name: 'TCDSB 7s and 8s' },
    { id: 'bishop-allen-academy', name: 'Bishop Allen Academy' },
    { id: 'bishop-marrocco-thomas-merton', name: 'Bishop Marrocco/Thomas Merton' },
    { id: 'brebeuf-college', name: 'Brebeuf College' },
    { id: 'cardinal-carter', name: 'Cardinal Carter' },
    { id: 'chaminade-college', name: 'Chaminade College' },
    { id: 'dante-alighieri-academy', name: 'Dante Alighieri Academy' },
    { id: 'father-henry-carr', name: 'Father Henry Carr' },
    { id: 'father-john-redmond', name: 'Father John Redmond' },
    { id: 'francis-libermann', name: 'Francis Libermann' },
    { id: 'james-cardinal-mcguigan', name: 'James Cardinal McGuigan' },
    { id: 'loretto-abbey', name: 'Loretto Abbey' },
    { id: 'loretto-college', name: 'Loretto College' },
    { id: 'madonna-catholic-secondary', name: 'Madonna Catholic Secondary' },
    { id: 'marshall-mcluhan', name: 'Marshall McLuhan' },
    { id: 'mary-ward', name: 'Mary Ward' },
    { id: 'michael-power-st-joseph', name: 'Michael Power/St. Joseph' },
    { id: 'monsignor-fraser-annex', name: 'Monsignor Fraser - Annex' },
    { id: 'monsignor-fraser-isabella', name: 'Monsignor Fraser - Isabella' },
    { id: 'monsignor-fraser-midland', name: 'Monsignor Fraser - Midland' },
    { id: 'monsignor-fraser-midtown', name: 'Monsignor Fraser - Midtown' },
    { id: 'monsignor-fraser-norfinch', name: 'Monsignor Fraser - Norfinch' },
    { id: 'monsignor-fraser-northeast', name: 'Monsignor Fraser - Northeast' },
    { id: 'monsignor-fraser-southwest', name: 'Monsignor Fraser - Southwest' },
    { id: 'monsignor-fraser-college-st-martin-campus', name: 'Monsignor Fraser College - St. Martin Campus' },
    { id: 'monsignor-percy-johnson', name: 'Monsignor Percy Johnson' },
    { id: 'neil-mcneil', name: 'Neil McNeil' },
    { id: 'notre-dame', name: 'Notre Dame' },
    { id: 'section-23', name: 'Section 23' },
    { id: 'senator-oconnor', name: "Senator O'Connor" },
    { id: 'st-anne-catholic-academy-virtual', name: 'St Anne Catholic Academy (Virtual)' },
    { id: 'st-basil', name: 'St. Basil' },
    { id: 'st-joan-of-arc-catholic-academy', name: 'St. Joan of Arc Catholic Academy' },
    { id: 'st-john-henry-newman', name: 'St. John Henry Newman' },
    { id: 'st-john-paul-ii-catholic-secondary-school', name: 'St. John Paul II Catholic Secondary School' },
    { id: 'st-josephs-morrow-park', name: "St. Joseph's Morrow Park" },
    { id: 'st-josephs-college', name: "St. Joseph's College" },
    { id: 'st-mary-catholic', name: 'St. Mary Catholic' },
    { id: 'st-michaels-choir', name: "St. Michael's Choir" },
    { id: 'st-mother-teresa-catholic-academy', name: 'St. Mother Teresa Catholic Academy' },
    { id: 'st-oscar-romero', name: 'St. Oscar Romero' },
    { id: 'st-patrick', name: 'St. Patrick' },
  ],
  'algoma-dsb': [
    { id: 'algoma-7s-and-8s', name: 'Algoma 7s and 8s' },
    { id: 'adult-and-continuing-ed-blind-river', name: 'Adult and Continuing Ed Blind River' },
    { id: 'alexander-henry-high-school', name: 'Alexander Henry High School' },
    { id: 'algoma-education-connection', name: 'Algoma Education Connection' },
    { id: 'alternative-programs', name: 'Alternative Programs' },
    { id: 'central-algoma-secondary', name: 'Central Algoma Secondary' },
    { id: 'chapleau-high-school', name: 'Chapleau High School' },
    { id: 'don-doucet-youth-centre', name: 'Don Doucet Youth Centre' },
    { id: 'elliot-lake-secondary-school', name: 'Elliot Lake Secondary School' },
    { id: 'hornepayne-high-school', name: 'Hornepayne High School' },
    { id: 'korah-collegiate-and-vocational-school', name: 'Korah Collegiate and Vocational School' },
    { id: 'michipicoten-high-school', name: 'Michipicoten High School' },
    { id: 'superior-heights-collegiate-and-vocational-school', name: 'Superior Heights Collegiate and Vocational School' },
    { id: 'wc-eaket-secondary-school', name: 'W.C. Eaket Secondary School' },
    { id: 'white-pines-cvs', name: 'White Pines C&VS' },
  ],
  'lambton-kent': [
    { id: 'lambton-kent-7s-and-8s', name: 'Lambton Kent 7s and 8s' },
    { id: 'alexander-mackenzie', name: 'Alexander Mackenzie' },
    { id: 'alternative-and-continuing-education-centre', name: 'Alternative and Continuing Education Centre' },
    { id: 'blenheim-district-hs', name: 'Blenheim District HS' },
    { id: 'chatham-kent-ss', name: 'Chatham-Kent SS' },
    { id: 'great-lakes-secondary-school', name: 'Great Lakes Secondary School' },
    { id: 'john-mcgregor', name: 'John McGregor' },
    { id: 'lambton-central-cvi', name: 'Lambton Central CVI' },
    { id: 'lambton-kent-virtual-secondary-school', name: 'Lambton Kent Virtual Secondary School' },
    { id: 'lambton-kent-composite', name: 'Lambton-Kent Composite' },
    { id: 'lkdsb-special-programs', name: 'LKDSB Special Programs' },
    { id: 'north-lambton', name: 'North Lambton' },
    { id: 'northern-collegiate-institute-and-vocational', name: 'Northern Collegiate Institute and Vocational' },
    { id: 'ridgetown-district', name: 'Ridgetown District' },
    { id: 'tilbury-district', name: 'Tilbury District' },
    { id: 'wallaceburg-district', name: 'Wallaceburg District' },
  ],
  'peel-dsb': [
    { id: 'peel-7s-and-8s', name: 'Peel 7s and 8s' },
    { id: 'applewood-heights-secondary', name: 'Applewood Heights Secondary' },
    { id: 'applewood-school', name: 'Applewood School' },
    { id: 'bramalea-secondary-school', name: 'Bramalea Secondary School' },
    { id: 'brampton-centennial-secondary-school', name: 'Brampton Centennial Secondary School' },
    { id: 'brampton-centennial-summer-school-in-person', name: 'Brampton Centennial Summer School (In-person)' },
    { id: 'castlebrooke-secondary-school', name: 'Castlebrooke Secondary School' },
    { id: 'castlebrooke-summer-school-in-person', name: 'Castlebrooke Summer School (In-person)' },
    { id: 'cawthra-park-secondary-school', name: 'Cawthra Park Secondary School' },
    { id: 'central-peel-secondary-school', name: 'Central Peel Secondary School' },
    { id: 'chinguacousy-secondary-school', name: 'Chinguacousy Secondary School' },
    { id: 'clarkson-secondary-school', name: 'Clarkson Secondary School' },
    { id: 'david-suzuki-secondary-school', name: 'David Suzuki Secondary School' },
    { id: 'david-suzuki-summer-school-online', name: 'David Suzuki Summer School (Online)' },
    { id: 'erindale-secondary-school', name: 'Erindale Secondary School' },
    { id: 'fletchers-meadow-secondary-school', name: 'Fletchers Meadow Secondary School' },
    { id: 'fletchers-meadow-summer-school-in-person', name: 'Fletchers Meadow Summer School (In-person)' },
    { id: 'glenforest-secondary-school', name: 'Glenforest Secondary School' },
    { id: 'harold-m-brathwaite-secondary-school', name: 'Harold M. Brathwaite Secondary School' },
    { id: 'heart-lake-secondary-school', name: 'Heart Lake Secondary School' },
    { id: 'humberview-secondary-school', name: 'Humberview Secondary School' },
    { id: 'jean-augustine-secondary-school', name: 'Jean Augustine Secondary School' },
    { id: 'jean-augustine-summer-school-remote', name: 'Jean Augustine Summer School (Remote)' },
    { id: 'john-fraser-secondary-school', name: 'John Fraser Secondary School' },
    { id: 'john-fraser-summer-school-online', name: 'John Fraser Summer School (Online)' },
    { id: 'judith-nyman-secondary-school', name: 'Judith Nyman Secondary School' },
    { id: 'lincoln-m-alexander-secondary-school', name: 'Lincoln M. Alexander Secondary School' },
    { id: 'lorne-park-secondary-school', name: 'Lorne Park Secondary School' },
    { id: 'louise-arbour-secondary-school', name: 'Louise Arbour Secondary School' },
    { id: 'louise-arbour-summer-school-online', name: 'Louise Arbour Summer School (Online)' },
    { id: 'mayfield-secondary-school', name: 'Mayfield Secondary School' },
    { id: 'meadowvale-secondary-school', name: 'Meadowvale Secondary School' },
    { id: 'mississauga-secondary-school', name: 'Mississauga Secondary School' },
    { id: 'mississauga-summer-school-remote', name: 'Mississauga Summer School (Remote)' },
    { id: 'north-park-secondary-school', name: 'North Park Secondary School' },
    { id: 'parkholme-school', name: 'Parkholme School' },
    { id: 'peel-adult-education-centre', name: 'Peel Adult Education Centre' },
    { id: 'peel-alternative-north-isr', name: 'Peel Alternative North ISR' },
    { id: 'peel-alternative-school-central', name: 'Peel Alternative School Central' },
    { id: 'peel-alternative-school-north', name: 'Peel Alternative School North' },
    { id: 'peel-alternative-school-south', name: 'Peel Alternative School South' },
    { id: 'peel-alternative-school-west', name: 'Peel Alternative School West' },
    { id: 'peel-alternative-south-isr', name: 'Peel Alternative South ISR' },
    { id: 'peel-alternative-west-isr', name: 'Peel Alternative West ISR' },
    { id: 'peel-special-programs', name: 'Peel Special Programs' },
    { id: 'peel-virtual-secondary-school', name: 'Peel Virtual Secondary School' },
    { id: 'port-credit-secondary-school', name: 'Port Credit Secondary School' },
    { id: 'rick-hansen-secondary-school', name: 'Rick Hansen Secondary School' },
    { id: 'rick-hansen-summer-school-in-person', name: 'Rick Hansen Summer School (In-person)' },
    { id: 's23-aysp-bramalea-ss', name: 'S23 AYSP/Bramalea S.S.' },
    { id: 's23-aysp-brampton-centennial-ss', name: 'S23 AYSP/Brampton Centennial S.S.' },
    { id: 's23-cornerstone-north-park-ss', name: 'S23 Cornerstone/North Park S.S.' },
    { id: 's23-full-circle-central-peel-sec', name: 'S23 Full Circle/Central Peel Sec' },
    { id: 's23-hanrahan-harold-brathwaite', name: 'S23 Hanrahan/Harold Brathwaite' },
    { id: 's23-johnsons-childrens-srv-rhss', name: 'S23 Johnsons Childrens Srv/RHSS' },
    { id: 's23-pcc-glenforest-ss', name: 'S23 PCC/Glenforest S.S.' },
    { id: 's23-pcc-glenhaven-sr-ps', name: 'S23 PCC/Glenhaven Sr. PS.' },
    { id: 's23-pcc-lpss', name: 'S23 PCC/LPSS' },
    { id: 's23-peel-sec-edu-centre-b-centennial', name: 'S23 Peel Sec Edu Centre/B Centennial' },
    { id: 's23-peel-sec-edu-centre-t-fenton', name: 'S23 Peel Sec Edu Centre/T. Fenton' },
    { id: 's23-spectrum-beatty-fleming-snr-ps', name: 'S23 Spectrum/Beatty Fleming Snr PS' },
    { id: 's23-spectrum-centennial-sr-ps', name: 'S23 Spectrum/Centennial Sr. PS.' },
    { id: 's23-spectrum-chinguacousy-ss', name: 'S23 Spectrum/Chinguacousy S.S.' },
    { id: 's23-spectrum-west-credit', name: 'S23 Spectrum/West Credit' },
    { id: 's23-tre-add-harold-brathwaite-sec', name: 'S23 TRE-ADD/Harold Brathwaite Sec' },
    { id: 's23-vanier-residence-glenforest-ss', name: 'S23 Vanier Residence/Glenforest SS' },
    { id: 's23-wm-osler-health-ctre-mayfield', name: 'S23 Wm Osler Health Ctre/Mayfield' },
    { id: 'sandalwood-heights-secondary-school', name: 'Sandalwood Heights Secondary School' },
    { id: 'stephen-lewis-secondary-school', name: 'Stephen Lewis Secondary School' },
    { id: 'stephen-lewis-summer-school-remote', name: 'Stephen Lewis Summer School (Remote)' },
    { id: 'streetsville-secondary-school', name: 'Streetsville Secondary School' },
    { id: 'summer-school-co-op', name: 'Summer School - CO-OP' },
    { id: 'tl-kennedy-secondary-school', name: 'T.L. Kennedy Secondary School' },
    { id: 'the-woodlands-school', name: 'The Woodlands School' },
    { id: 'turner-fenton-secondary-school', name: 'Turner Fenton Secondary School' },
    { id: 'west-credit-secondary-school', name: 'West Credit Secondary School' },
  ],
  'renfrew-county': [
    { id: 'renfrew-county-7s-and-8s', name: 'Renfrew County 7s and 8s' },
    { id: 'adult-day-school', name: 'Adult Day School' },
    { id: 'arnprior-district-high-school', name: 'Arnprior District High School' },
    { id: 'continuing-education', name: 'Continuing Education' },
    { id: 'fellowes-high-school', name: 'Fellowes High School' },
    { id: 'lbs', name: 'LBS' },
    { id: 'mackenzie-community-school', name: 'Mackenzie Community School' },
    { id: 'madawaska-valley-district-school', name: 'Madawaska Valley District School' },
    { id: 'opeongo-high-school', name: 'Opeongo High School' },
    { id: 'renfrew-collegiate-institute', name: 'Renfrew Collegiate Institute' },
    { id: 'valour-jk-12-school', name: 'Valour JK – 12 School' },
  ],
  'hamilton-wentworth': [
    { id: 'hamilton-wentworth-7s-and-8s', name: 'Hamilton-Wentworth 7s and 8s' },
    { id: 'adult-on-line-night-school', name: 'Adult On-Line Night School' },
    { id: 'ancaster-high-school', name: 'Ancaster High School' },
    { id: 'arrell-youth-centre', name: 'Arrell Youth Centre' },
    { id: 'bernie-custis-secondary-school', name: 'Bernie Custis Secondary School' },
    { id: 'bridge-program-1-2', name: 'Bridge Program 1 & 2' },
    { id: 'continuing-education-hwdsb', name: 'Continuing Education HWDSB' },
    { id: 'dundas-valley-secondary-school', name: 'Dundas Valley Secondary School' },
    { id: 'george-r-force', name: 'George R. Force' },
    { id: 'glendale-secondary-school', name: 'Glendale Secondary School' },
    { id: 'grace-haven', name: 'Grace Haven' },
    { id: 'hatts-off-4-secondary', name: 'Hatts Off # 4 Secondary' },
    { id: 'hill-park-system-alternative-education', name: 'Hill Park System Alternative Education' },
    { id: 'international-languages', name: 'International Languages' },
    { id: 'james-street', name: 'James Street' },
    { id: 'john-howard', name: 'John Howard' },
    { id: 'lynwood-charlton-centre-compass-secondary', name: 'Lynwood Charlton Centre Compass Secondary' },
    { id: 'lynwood-charlton-centre-flamborough-school', name: 'Lynwood Charlton Centre Flamborough School' },
    { id: 'mcmaster-childrens-hospital', name: "McMaster Children's Hospital" },
    { id: 'nora-frances-henderson', name: 'Nora Frances Henderson' },
    { id: 'orchard-park-secondary-school', name: 'Orchard Park Secondary School' },
    { id: 'rebecca-st', name: 'Rebecca St.' },
    { id: 'saltfleet-high-school', name: 'Saltfleet High School' },
    { id: 'sherwood-secondary', name: 'Sherwood Secondary' },
    { id: 'sir-allan-macnab-secondary-school', name: 'Sir Allan MacNab Secondary School' },
    { id: 'sir-winston-churchill-secondary-school', name: 'Sir Winston Churchill Secondary School' },
    { id: 'turning-point', name: 'Turning Point' },
    { id: 'waterdown-district-high', name: 'Waterdown District High' },
    { id: 'westdale-secondary-school', name: 'Westdale Secondary School' },
    { id: 'westmount-secondary-school', name: 'Westmount Secondary School' },
    { id: 'woodview-day-program', name: 'Woodview Day Program' },
  ],
  'upper-grand': [
    { id: 'upper-grand-7s-and-8s', name: 'Upper Grand 7s and 8s' },
    { id: 'ariss-place', name: 'Ariss Place' },
    { id: 'avalon-horizons', name: 'Avalon Horizons' },
    { id: 'avalon-specialized-services', name: 'Avalon Specialized Services' },
    { id: 'cedar-heights', name: 'Cedar Heights' },
    { id: 'centennial-cvi', name: 'Centennial CVI' },
    { id: 'centre-dufferin-dhs', name: 'Centre Dufferin DHS' },
    { id: 'centre-wellington-dhs', name: 'Centre Wellington DHS' },
    { id: 'college-heights-ss', name: 'College Heights SS' },
    { id: 'continuing-education-dufferin-centre', name: 'Continuing Education, Dufferin Centre' },
    { id: 'continuing-education-guelph', name: 'Continuing Education, Guelph' },
    { id: 'dufferin-gr-8-reach-ahead-in-person', name: 'Dufferin Gr. 8 Reach Ahead (In-person)' },
    { id: 'dufferin-summer-school-in-person', name: 'Dufferin Summer School (In-person)' },
    { id: 'dufferin-summer-school-upgrading-in-person', name: 'Dufferin Summer School Upgrading (In-person)' },
    { id: 'e-learning-gr-8-reach-ahead', name: 'E-Learning Gr. 8 Reach Ahead' },
    { id: 'erin-dhs', name: 'Erin D.H.S.' },
    { id: 'gateway-trellis', name: 'Gateway Trellis' },
    { id: 'give-yourself-credit', name: 'Give Yourself Credit' },
    { id: 'guelph-cvi', name: 'Guelph C.V.I.' },
    { id: 'guelph-gr-8-reach-ahead-in-person', name: 'Guelph Gr. 8 Reach Ahead (In-person)' },
    { id: 'guelph-summer-school-in-person', name: 'Guelph Summer School (In-person)' },
    { id: 'guelph-summer-school-upgrading-in-person', name: 'Guelph Summer School Upgrading (In-person)' },
    { id: 'hopewell', name: 'Hopewell' },
    { id: 'john-f-ross-cvi', name: 'John F. Ross C.V.I.' },
    { id: 'new-high-school-guelph-2026', name: 'New High School Guelph (2026)' },
    { id: 'new-way', name: 'New Way' },
    { id: 'night-school-fall-2025', name: 'Night School Fall 2025' },
    { id: 'norwell-dss', name: 'Norwell D.S.S.' },
    { id: 'orangeville-dss', name: 'Orangeville D.S.S' },
    { id: 'orangeville-night-school-fall-2025', name: 'Orangeville Night School Fall 2025' },
    { id: 'pine-river-institute', name: 'Pine River Institute' },
    { id: 'portage-academy', name: 'Portage Academy' },
    { id: 'secondary-remote-school-upper-grand', name: 'Secondary Remote School' },
    { id: 'ugdsb-alternative-education-at-chss', name: 'UGDSB Alternative Education @ CHSS' },
    { id: 'upper-grand-secondary-school', name: 'Upper Grand Secondary School' },
    { id: 'wellington-heights-ss', name: 'Wellington Heights S.S.' },
    { id: 'westside-ss', name: 'Westside S.S.' },
    { id: 'youth-options', name: 'Youth Options' },
  ],
  'ottawa-catholic': [
    { id: 'ottawa-catholic-7s-and-8s', name: 'Ottawa Catholic 7s and 8s' },
    { id: 'all-saints-high-school', name: 'All Saints High School' },
    { id: 'holy-trinity-high-school', name: 'Holy Trinity High School' },
    { id: 'immaculata-high-school', name: 'Immaculata High School' },
    { id: 'lester-b-pearson-high-school', name: 'Lester B. Pearson High School' },
    { id: 'mf-mchugh-education-centre', name: 'M.F. McHugh Education Centre' },
    { id: 'mchugh-high-school', name: 'McHugh High School' },
    { id: 'notre-dame-high-school', name: 'Notre Dame High School' },
    { id: 'ocsb-achievement-centres', name: 'OCSB Achievement Centres' },
    { id: 'sacred-heart-high-school', name: 'Sacred Heart High School' },
    { id: 'st-francis-xavier-high-school', name: 'St. Francis Xavier High School' },
    { id: 'st-joseph-high-school', name: 'St. Joseph High School' },
    { id: 'st-josephine-virtual-high-school', name: 'St. Josephine Virtual High School' },
    { id: 'st-mark-high-school', name: 'St. Mark High School' },
    { id: 'st-matthew-high-school', name: 'St. Matthew High School' },
    { id: 'st-mother-teresa-high-school', name: 'St. Mother Teresa High School' },
    { id: 'st-nicholas-high-school', name: 'St. Nicholas High School' },
    { id: 'st-patricks-high-school', name: "St. Patrick's High School" },
    { id: 'st-paul-high-school', name: 'St. Paul High School' },
    { id: 'st-peter-high-school', name: 'St. Peter High School' },
    { id: 'st-pius-x-high-school', name: 'St. Pius X High School' },
  ],
  'northeastern-cdsb': [
    { id: 'northeastern-7s-and-8s', name: 'Northeastern 7s and 8s' },
  ],
  'algonquin-lakeshore': [
    { id: 'algonquin-lakeshore-7s-and-8s', name: 'Algonquin & Lakeshore 7s and 8s' },
    { id: 'holy-cross', name: 'Holy Cross' },
    { id: 'loyola-community-learning-centre', name: 'Loyola Community Learning Centre' },
    { id: 'nicholson-catholic-college', name: 'Nicholson Catholic College' },
    { id: 'regiopolis-notre-dame', name: 'Regiopolis-Notre Dame' },
    { id: 'st-paul-catholic-ss', name: 'St. Paul Catholic S.S.' },
    { id: 'st-theresa-catholic-ss', name: 'St. Theresa Catholic S.S.' },
  ],
  'dsbone': [
    { id: 'dsbone-7s-and-8s', name: 'DSBONE 7s and 8s' },
    { id: 'ecole-secondaire-cochrane-high-school', name: 'Ecole Secondaire Cochrane High School' },
    { id: 'englehart-high-school', name: 'Englehart High School' },
    { id: 'hearst-high-school', name: 'Hearst High School' },
    { id: 'iroquois-falls-secondary-school', name: 'Iroquois Falls Secondary School' },
    { id: 'kapuskasing-dhs', name: 'Kapuskasing DHS' },
    { id: 'kirkland-lake-district-composite-school', name: 'Kirkland Lake District Composite School' },
    { id: 'pace-programmes-for-adult-and-continuing-education', name: 'PACE (Programmes for Adult and Continuing Education)' },
    { id: 'roland-michener-secondary-school', name: 'Roland Michener Secondary School' },
    { id: 'smooth-rock-falls', name: 'Smooth Rock Falls' },
    { id: 'timiskaming-district-secondary-school', name: 'Timiskaming District Secondary School' },
    { id: 'timmins-high-and-vocational-school', name: 'Timmins High and Vocational School' },
  ],
  'simcoe-county': [
    { id: 'simcoe-county-7s-and-8s', name: 'Simcoe County 7s and 8s' },
    { id: 'banting-memorial-high-school', name: 'Banting Memorial High School' },
    { id: 'barrie-north-collegiate-institute', name: 'Barrie North Collegiate Institute' },
    { id: 'bear-creek-secondary-school', name: 'Bear Creek Secondary School' },
    { id: 'bradford-district-high-school', name: 'Bradford District High School' },
    { id: 'collingwood-collegiate-institute', name: 'Collingwood Collegiate Institute' },
    { id: 'eastview-secondary-school', name: 'Eastview Secondary School' },
    { id: 'elmvale-district-high-school', name: 'Elmvale District High School' },
    { id: 'georgian-bay-district-secondary-school', name: 'Georgian Bay District Secondary School' },
    { id: 'innisdale-secondary-school', name: 'Innisdale Secondary School' },
    { id: 'maple-ridge-secondary-school', name: 'Maple Ridge Secondary School' },
    { id: 'nantyr-shores-secondary-school', name: 'Nantyr Shores Secondary School' },
    { id: 'north-simcoe-secondary-school', name: 'North Simcoe Secondary School' },
    { id: 'nottawasaga-pines-secondary-school', name: 'Nottawasaga Pines Secondary School' },
    { id: 'orillia-secondary-school', name: 'Orillia Secondary School' },
    { id: 'penetanguishene-secondary-school', name: 'Penetanguishene Secondary School' },
    { id: 'simcoe-academy', name: 'Simcoe Academy' },
    { id: 'simcoe-shores-secondary-school', name: 'Simcoe Shores Secondary School' },
    { id: 'stayner-collegiate-institute', name: 'Stayner Collegiate Institute' },
    { id: 'the-learning-centres', name: 'The Learning Centres' },
    { id: 'twin-lakes-secondary-school', name: 'Twin Lakes Secondary School' },
  ],
  'york-catholic': [
    { id: 'york-catholic-7s-and-8s', name: 'York Catholic 7s and 8s' },
    { id: 'cardinal-carter-chs', name: 'Cardinal Carter CHS' },
    { id: 'father-bressani', name: 'Father Bressani' },
    { id: 'father-michael-mcgivney-ca', name: 'Father Michael McGivney CA' },
    { id: 'holy-cross-york', name: 'Holy Cross' },
    { id: 'our-lady-of-the-lake', name: 'Our Lady of the Lake' },
    { id: 'our-lady-queen-of-the-world', name: 'Our Lady Queen of the World' },
    { id: 'sacred-heart-york', name: 'Sacred Heart' },
    { id: 'st-augustine', name: 'St. Augustine' },
    { id: 'st-brother-andre', name: 'St. Brother André' },
    { id: 'st-elizabeth', name: 'St. Elizabeth' },
    { id: 'st-jean-de-brebeuf', name: 'St. Jean de Brebeuf' },
    { id: 'st-joan-of-arc-york', name: 'St. Joan of Arc' },
    { id: 'st-katharine-drexel', name: 'St. Katharine Drexel' },
    { id: 'st-luke-catholic-learning-centre', name: 'St. Luke Catholic Learning Centre' },
    { id: 'st-maximilian-kolbe', name: 'St. Maximilian Kolbe' },
    { id: 'st-robert', name: 'St. Robert' },
    { id: 'st-teresa-of-calcutta', name: 'St. Teresa of Calcutta' },
    { id: 'st-theresa-of-lisieux', name: 'St. Theresa of Lisieux' },
    { id: 'york-academy', name: 'York Academy' },
  ],
  'pvnc-dsb': [
    { id: 'pvnc-7s-and-8s', name: 'PVNC 7s and 8s' },
    { id: 'day-school-e-learning', name: 'Day School e-Learning' },
    { id: 'enterphase', name: 'Enterphase' },
    { id: 'enterphase-child-and-family-services', name: 'Enterphase Child and Family Services' },
    { id: 'holy-cross-catholic-secondary-school', name: 'Holy Cross Catholic Secondary School' },
    { id: 'holy-trinity-catholic-secondary-school', name: 'Holy Trinity Catholic Secondary School' },
    { id: 'night-school', name: 'Night School' },
    { id: 'st-mary-catholic-secondary-school', name: 'St. Mary Catholic Secondary School' },
    { id: 'st-peter-catholic-secondary-school', name: 'St. Peter Catholic Secondary School' },
    { id: 'st-stephen-catholic-secondary-school', name: 'St. Stephen Catholic Secondary School' },
    { id: 'st-thomas-aquinas-catholic-secondary-school', name: 'St. Thomas Aquinas Catholic Secondary School' },
    { id: 'st-thomas-aquinas-virtual-catholic-secondary-school', name: 'St. Thomas Aquinas Virtual Catholic Secondary School' },
  ],
  'durham-dsb': [
    { id: 'durham-7s-and-8s', name: 'Durham 7s and 8s' },
    { id: 'ajax-high-school', name: 'Ajax High School' },
    { id: 'anderson-collegiate-and-vocational-institute', name: 'Anderson Collegiate and Vocational Institute' },
    { id: 'brock-high-school', name: 'Brock High School' },
    { id: 'brooklin-high-school', name: 'Brooklin High School' },
    { id: 'ddsb-at-home-secondary', name: 'DDSB @Home - Secondary' },
    { id: 'donald-a-wilson-secondary-school', name: 'Donald A. Wilson Secondary School' },
    { id: 'dunbarton-high-school', name: 'Dunbarton High School' },
    { id: 'durham-alternative-secondary-school', name: 'Durham Alternative Secondary School' },
    { id: 'durham-centres-for-success', name: 'Durham Centres for Success' },
    { id: 'eastdale-collegiate-and-vocational-institute', name: 'Eastdale Collegiate and Vocational Institute' },
    { id: 'gl-roberts-collegiate-and-vocational-institute', name: 'G.L. Roberts Collegiate and Vocational Institute' },
    { id: 'grove-school', name: 'Grove School' },
    { id: 'henry-street-high-school', name: 'Henry Street High School' },
    { id: 'j-clarke-richardson-collegiate', name: 'J.Clarke Richardson Collegiate' },
    { id: 'maxwell-heights-secondary-school', name: 'Maxwell Heights Secondary School' },
    { id: 'oneill-collegiate-and-vocational-institute', name: "O'Neill Collegiate and Vocational Institute" },
    { id: 'pickering-high-school', name: 'Pickering High School' },
    { id: 'pine-ridge-secondary-school', name: 'Pine Ridge Secondary School' },
    { id: 'port-perry-high-school', name: 'Port Perry High School' },
    { id: 'rs-mclaughlin-collegiate-and-vocational-institute', name: 'R.S. McLaughlin Collegiate and Vocational Institute' },
    { id: 'sinclair-secondary-school', name: 'Sinclair Secondary School' },
    { id: 'uxbridge-secondary-school', name: 'Uxbridge Secondary School' },
  ],
  'bruce-grey-catholic': [
    { id: 'bruce-grey-catholic-7s-and-8s', name: 'Bruce-Grey Catholic 7s and 8s' },
    { id: 'continuing-education-bruce-grey', name: 'Continuing Education' },
    { id: 'sacred-heart-high-school', name: 'Sacred Heart High School' },
    { id: 'st-marys-high-school', name: "St. Mary's High School" },
  ],
  'greater-essex-country': [
    { id: 'greater-essex-country-7s-and-8s', name: 'Greater Essex Country 7s and 8s' },
    { id: 'adult-and-continuing-education', name: 'Adult and Continuing Education' },
    { id: 'belle-river-district-high-school', name: 'Belle River District High School' },
    { id: 'erie-migration-district-school', name: 'Erie Migration District School' },
    { id: 'essex-district-high-school', name: 'Essex District High School' },
    { id: 'hon-wc-kennedy-collegiate', name: 'Hon. W. C. Kennedy Collegiate' },
    { id: 'leamington-district-secondary', name: 'Leamington District Secondary' },
    { id: 'north-star-high-school', name: 'North Star High School' },
    { id: 'public-alternative-secondary-school', name: 'Public Alternative Secondary School' },
    { id: 'riverside-secondary-school', name: 'Riverside Secondary School' },
    { id: 'sandwich-secondary', name: 'Sandwich Secondary' },
    { id: 'tecumseh-vista-academy', name: 'Tecumseh Vista Academy' },
    { id: 'vincent-massey-secondary', name: 'Vincent Massey Secondary' },
    { id: 'virtual-school', name: 'Virtual School' },
    { id: 'wf-herman-academy', name: 'W.F. Herman Academy' },
    { id: 'walkerville-centre-for-the-creative-arts', name: 'Walkerville Centre for the Creative Arts' },
    { id: 'walkerville-collegiate-institute', name: 'Walkerville Collegiate Institute' },
    { id: 'westview-freedom-academy', name: 'Westview Freedom Academy' },
  ],
  'keewatin-patricia': [
    { id: 'keewatin-patricia-7s-and-8s', name: 'Keewatin-Patricia 7s and 8s' },
    { id: 'adult-education', name: 'Adult Education' },
    { id: 'alternative-education', name: 'Alternative Education' },
    { id: 'beaver-brae-ss', name: 'Beaver Brae SS' },
    { id: 'crolancia-secondary', name: 'Crolancia Secondary' },
    { id: 'dryden-high-school-keewatin', name: 'Dryden High School' },
    { id: 'ignace-high-school', name: 'Ignace High School' },
    { id: 'kenora-attendance-centre', name: 'Kenora Attendance Centre' },
    { id: 'kenora-rainy-river', name: 'Kenora Rainy-River' },
    { id: 'red-lake-district-high-school', name: 'Red Lake District High School' },
    { id: 'secondary-digital-learning-school', name: 'Secondary Digital Learning School' },
    { id: 'sioux-north-hs', name: 'Sioux North HS' },
  ],
  'cdsb-eastern-ontario': [
    { id: 'cdsb-eastern-ontario-7s-and-8s', name: 'CDSB Eastern Ontario 7s and 8s' },
    { id: 'holy-trinity-css', name: 'Holy Trinity CSS' },
    { id: 'notre-dame-chs', name: 'Notre Dame CHS' },
    { id: 'st-francis-xavier-chs', name: 'St. Francis Xavier CHS' },
    { id: 'st-james-cec', name: 'St. James CEC' },
    { id: 'st-john-chs', name: 'St. John CHS' },
    { id: 'st-joseph-css', name: 'St. Joseph CSS' },
    { id: 'st-luke-chs', name: 'St. Luke CHS' },
    { id: 'st-mary-chs', name: 'St. Mary CHS' },
    { id: 'st-matthew-css', name: 'St. Matthew CSS' },
    { id: 'st-michael-chs', name: 'St. Michael CHS' },
    { id: 'st-thomas-aquinas-chs', name: 'St. Thomas Aquinas CHS' },
  ],
  'waterloo-region': [
    { id: 'wrdsb-7s-and-8s', name: 'WRDSB 7s and 8s' },
    { id: 'ace', name: 'ACE' },
    { id: 'alternative-choices', name: 'Alternative Choices' },
    { id: 'blair-outdoor-and-environmental-education-centre', name: 'Blair Outdoor and Environmental Education Centre' },
    { id: 'bluevale-collegiate-institute', name: 'Bluevale Collegiate Institute' },
    { id: 'cameron-heights-collegiate-institute', name: 'Cameron Heights Collegiate Institute' },
    { id: 'camp-heidelberg-outdoor-and-environmental-education-centre', name: 'Camp Heidelberg Outdoor and Environmental Education Centre' },
    { id: 'eastwood-collegiate-institute', name: 'Eastwood Collegiate Institute' },
    { id: 'elmira-district-secondary-school', name: 'Elmira District Secondary School' },
    { id: 'esu-essential-skills-upgrading', name: 'ESU: Essential Skills Upgrading' },
    { id: 'forest-heights-collegiate-institute', name: 'Forest Heights Collegiate Institute' },
    { id: 'galt-collegiate-institute-vocational-school', name: 'Galt Collegiate Institute & Vocational School' },
    { id: 'glenview-park-secondary-school', name: 'Glenview Park Secondary School' },
    { id: 'grand-river-collegiate-institute', name: 'Grand River Collegiate Institute' },
    { id: 'huron-heights-ss', name: 'Huron Heights S.S.' },
    { id: 'huron-natural-area-outdoor-environmental-education-centre', name: 'Huron Natural Area Outdoor Environmental Education Centre' },
    { id: 'jacob-hespeler-secondary-school', name: 'Jacob Hespeler Secondary School' },
    { id: 'kitchener-waterloo-collegiate-vocational-school', name: 'Kitchener-Waterloo Collegiate & Vocational School' },
    { id: 'laurel-creek-conservation-area', name: 'Laurel Creek Conservation Area' },
    { id: 'laurel-heights-secondary-school', name: 'Laurel Heights Secondary School' },
    { id: 'laurentian-senior-public-school', name: 'Laurentian Senior Public School' },
    { id: 'preston-high-school', name: 'Preston High School' },
    { id: 'rosemount-family-of-schools', name: 'Rosemount Family of Schools' },
    { id: 'southwood-secondary-school', name: 'Southwood Secondary School' },
    { id: 'uturn-cambridge', name: 'UTurn Cambridge' },
    { id: 'uturn-waterloo', name: 'UTurn Waterloo' },
    { id: 'waterloo-collegiate-institute', name: 'Waterloo Collegiate Institute' },
    { id: 'waterloo-oxford-district-secondary-school', name: 'Waterloo-Oxford District Secondary School' },
    { id: 'wrigley-corners-outdoor-and-environmental-education-centre', name: 'Wrigley Corners Outdoor and Environmental Education Centre' },
  ],
  'thames-valley': [
    { id: 'thames-valley-7s-and-8s', name: 'Thames Valley 7s and 8s' },
    { id: 'ab-lucas-secondary-school', name: 'A.B. Lucas Secondary School' },
    { id: 'arthur-voaden-secondary-school', name: 'Arthur Voaden Secondary School' },
    { id: 'central-elgin-collegiate-institute', name: 'Central Elgin Collegiate Institute' },
    { id: 'clarke-road-secondary-school', name: 'Clarke Road Secondary School' },
    { id: 'college-avenue-secondary-school', name: 'College Avenue Secondary School' },
    { id: 'east-elgin-secondary-school', name: 'East Elgin Secondary School' },
    { id: 'ga-wheable', name: 'G.A. Wheable' },
    { id: 'glencoe-district-high-school', name: 'Glencoe District High School' },
    { id: 'glendale-high-school', name: 'Glendale High School' },
    { id: 'hb-beal-secondary-school', name: 'H.B. Beal Secondary School' },
    { id: 'huron-park-secondary-school', name: 'Huron Park Secondary School' },
    { id: 'ingersoll-district-collegiate-institute', name: 'Ingersoll District Collegiate Institute' },
    { id: 'london-central-secondary-school', name: 'London Central Secondary School' },
    { id: 'london-south-collegiate', name: 'London South Collegiate' },
    { id: 'lord-dorchester-secondary-school', name: 'Lord Dorchester Secondary School' },
    { id: 'medway-high-school', name: 'Medway High School' },
    { id: 'montcalm-secondary-school', name: 'Montcalm Secondary School' },
    { id: 'north-middlesex-district-high-school', name: 'North Middlesex District High School' },
    { id: 'oakridge-secondary-school', name: 'Oakridge Secondary School' },
    { id: 'parkside-collegiate-institute', name: 'Parkside Collegiate Institute' },
    { id: 'remote-learning-secondary-school', name: 'Remote Learning Secondary School' },
    { id: 'saunders-secondary-school', name: 'Saunders Secondary School' },
    { id: 'sir-frederick-banting-secondary-school', name: 'Sir Frederick Banting Secondary School' },
    { id: 'sir-wilfrid-laurier-secondary-school', name: 'Sir Wilfrid Laurier Secondary School' },
    { id: 'strathroy-district-collegiate-institute', name: 'Strathroy District Collegiate Institute' },
    { id: 'thames-valley-alternative-secondary-school', name: 'Thames Valley Alternative Secondary School' },
    { id: 'wd-sutton-school', name: 'W.D. Sutton School' },
    { id: 'west-elgin-secondary-school', name: 'West Elgin Secondary School' },
    { id: 'westminster-secondary-school', name: 'Westminster Secondary School' },
    { id: 'woodstock-collegiate-institute', name: 'Woodstock Collegiate Institute' },
  ],
  'smithville-christian': [
    { id: 'smithville-christian', name: 'Smithville Christian' },
  ],
  'trinity-college-school': [
    { id: 'trinity-college-school', name: 'Trinity College School' },
  ],
};

export const CLASS_SIZES = [
  { id: 'less-than-25', label: 'Less than 25 students' },
  { id: '25-to-35', label: '25 to 35 students' },
  { id: 'large-group', label: 'Large group (35+ students)' },
];

export const GRADE_LEVELS = [
  { id: '7', label: 'Grade 7' },
  { id: '8', label: 'Grade 8' },
  { id: '9', label: 'Grade 9' },
  { id: '10', label: 'Grade 10' },
  { id: '11', label: 'Grade 11' },
  { id: '12', label: 'Grade 12' },
];
